bounds:
  n0.syn_weight n1: !!python/tuple
  - 1.0E-8
  - 10.
  n0.syn_weight n2: !!python/tuple
  - 1.0E-8
  - 10.
  n1.syn_weight n2: !!python/tuple
  - -10.
  - -1.0E-8
feature_names:
- n2.EPSP
- n2.IPSP
update_context:
  optimize_simple_ring: update_context_simple_ring
get_features_stages:
- source: optimize_simple_ring
  compute_features: compute_features_simple_ring
get_objectives:
  optimize_simple_ring: get_objectives_simple_ring
kwargs:
  network_config_file: config/Full_Scale_Control_log_normal_weights.yaml
  template_paths:
  dataset_prefix:
  results_path:
  results_id: None
  node_rank_file: None
  io_size: 0
  vrecord_fraction: 0
  coredat: False
  tstop: 0
  v_init: -65
  max_walltime_hours: 0
  results_write_time: 0
  dt: 0.025
  ldbal: False
  lptbal: False
  verbose: True
objective_names:
- n2.EPSP
- n2.IPSP
optimization_title: simple_ring
param_gen: PopulationAnnealing
param_names:
- n0.syn_weight n1
- n0.syn_weight n2
- n1.syn_weight n2
target_range:
  n2.EPSP: 3.
  n2.IPSP: 3.
target_val:
  n2.EPSP: 10.
  n2.IPSP: -5.
x0:
  n0.syn_weight n1: 0.01
  n0.syn_weight n2: 0.01
  n1.syn_weight n2: -0.01