bounds:
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-7
feature_names:
- iEPSP_i_unit
- iEPSP_attenuation_short
- iEPSP_attenuation_long
update_context:
- - optimize_DG_GC_iEPSP_propagation
  - reset_biophysics
get_features_stages:
- source: optimize_DG_GC_iEPSP_propagation
  compute_features: compute_features_iEPSP_i_unit
- source: optimize_DG_GC_iEPSP_propagation
  compute_features: compute_features_iEPSP_attenuation
  get_args_dynamic: get_args_dynamic_iEPSP_attenuation
get_objectives:
  optimize_DG_GC_iEPSP_propagation: get_objectives_iEPSP_propagation
kwargs:
  mech_file_path: mechanisms/20180529_DG_GC_mech.yaml
  gid: 0
  cell_type: GC
  correct_for_spines: True
  verbose: 2
  daspk: True
  configFile: ../dentate/config/Small_Scale_Control_log_normal_weights.yaml
  templatePaths: ../dgc/Mateos-Aparicio2014:../dentate/templates
  hoclibPath: ../dentate
  # datasetPrefix: /mnt/s
  datasetPrefix: ../dentate/datasets
  resultsPath: data
objective_names:
- iEPSP_attenuation_short
- iEPSP_attenuation_long
optimization_title: DG_GC_iEPSP_propagation
param_gen: PopulationAnnealing
param_names:
- soma.g_pas
target_range:
target_val:
  iEPSP_unit_amp: 1.
  iEPSP_attenuation_short: 0.17
  iEPSP_attenuation_long: 0.23
x0:
  soma.g_pas: 1.050E-10