bounds:
  dend.g_pas slope: !!python/tuple
  - 1.0E-10
  - 1.0E-5
  dend.g_pas tau: !!python/tuple
  - 25.
  - 400.
  soma.g_pas: !!python/tuple
  - 1.0E-12
  - 1.0E-7
feature_names:
- dend R_inp
- distal_dend R_inp
- soma R_inp
update_context:
  optimize_DG_GC_leak_hoc: update_context_leak
get_features_stages:
- source: optimize_DG_GC_leak_hoc
  compute_features: compute_features_leak
  get_args_static: get_args_static_leak
get_objectives:
  optimize_DG_GC_leak_hoc: get_objectives_leak
kwargs:
  mech_file_path: cells/mechanisms/090717 GC optimizing spiking.yaml
  neuroH5_file_path: cells/morphologies/121516_DGC_trees.pkl
  neuroH5_index: 0
  spines: False
  cvode: True
  verbose: True
  daspk: True
  config_file: ../dentate/config/Small_Scale_Control_log_normal_weights.yaml
  template_paths: ../dgc/Mateos-Aparicio2014
  hoc_templates_path: ../dentate
  dataset_prefix: ../dentate/datasets
  results_path: data
objective_names:
- dend R_inp
- distal_dend R_inp
- soma R_inp
optimization_title: DG_GC_leak_hoc
param_gen: PopulationAnnealing
param_names:
- dend.g_pas slope
- dend.g_pas tau
- soma.g_pas
target_range:
  dend R_inp: 1.
  soma R_inp: 0.5
target_val:
  dend R_inp: 375.
  soma R_inp: 295.
x0:
  dend.g_pas slope: 1.058E-08
  dend.g_pas tau: 3.886E+01
  soma.g_pas: 1.050E-10